### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by valeriu-dev** [greensun7/tilda-php#1]
будет ли возможность установить зависимость через composer?

**Comment by islandfuture** [comment]
файла .composer в репозитории нет, поэтому зависимости не получится через него установить.
здесь не используются сторонние библиотеки, только php и несколько модулей php_curl, php_json, php_mbstring
вроде все - при первом запуске все ошибки покажутся и можно будет доставить то чего не хватает

**Comment by valeriu-dev** [comment]
имел в виду не другие зависимости

**Comment by valeriu-dev** [comment]
переформулирую вопрос: можно установить библиотеку tilda-php через composer в свой проект как зависимость?

т.е. скачать через composer
